version: "3.8"
services:
  db:
    image: library/postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ../var/postgres-data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:6.5.6
    command: migrate
    environment:
      FLYWAY_EDITION: community
      FLYWAY_DEFAULT_SCHEMA: ${DATABASE_SCHEMA}
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
      FLYWAY_URL: jdbc:postgresql://db/${DATABASE_NAME}
    volumes:
    - ../flyway/sql:/flyway/sql
    - ../flyway/conf:/flyway/conf
    depends_on:
      - db
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_NAME}?sslmode=disable
    depends_on:
      - db
